# Generated by Django 4.1 on 2023-11-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_brand_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=255, null=True, verbose_name='ЦВет'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение4'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=255, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
