# Generated by Django 4.1 on 2023-11-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_image2_alter_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение4'),
        ),
    ]
